apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
        system: {{  .Values.systemLabel}} 
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-vote-back
        image: {{  .Values.imageRepo}}/azure-vote-back:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: Test
          value: "test12211"  
        ports:
        - containerPort: 6379
          name: redis