# Pipeline template to run linting, unit tests with code coverage, and publish the results.
# Pipeline to run basic code quality tests as part of pull requests to the master branch.

resources:
  containers:
    - container: mlops
      image: mcr.microsoft.com/mlops/python:latest
trigger: none

pr:
  branches:
    include:
      - master

pool:
  vmImage: "ubuntu-latest"

container: mlops

steps:
  - template: code-quality-template.yml
  - task: Bash@3
    name: "compile_pipeline"
    displayName: "Compile Pipeline"
    - script: |
      flake8 code --output-file=lint-testresults.xml --format junit-xml
    displayName: "Run lint tests"


  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: "*-testresults.xml"
      testRunTitle: "Linting & Unit tests"
      failTaskOnFailedTests: true
    displayName: "Publish test results"

  # - task: PublishCodeCoverageResults@1

  #   displayName: "Publish coverage report"

  #   condition: succeededOrFailed()

  #   inputs:

  #     codeCoverageTool: Cobertura

  #     summaryFileLocation: "coverage.xml"

  #     reportDirectory: "htmlcov"

  #     failIfCoverageEmpty: true