pr: none
trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

stages:
  stage: "Build_Push_Azure_Vote_App_Image"
    displayName: 'Build and Push Azure Vote App Image'    
    jobs:
      - job: "Build Image"
        steps:
          