pr: none
trigger:
  branches:
    include:
      - master
variables:
  - group: az-vote-app-dev

pool:
  vmImage: ubuntu-latest


stages:
  - stage: "Build_Push_Azure_Vote_App_Image"
    displayName: "Build and Push Azure Vote App Image"
    jobs:
      - job: "Build_Push_Vote_App_Image"
        displayName: "Build Push Vote-App Image"
        steps:
         
          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscription: '$(az_subcription_id)'
              azureContainerRegistry: '$(az_acr_name)'
              dockerComposeFile: '**/docker-compose.yaml'
              action: 'Build services'
          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscription: '$(az_subcription_id)'
              azureContainerRegistry: $(az_acr_name)'
              dockerComposeFile: '**/docker-compose.yaml'
              action: 'Push services'
                      
               
              
              
              
           
           
           