pr: none
trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest


stages:
  - stage: "Build_Push_Azure_Vote_App_Image"
    displayName: "Build and Push Azure Vote App Image"
    jobs:
      - job: "Code_Quality_Check"
        displayName: "Code Quality Check"        
        steps:
          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscription: 'davete-team(0fe1cc35-0cfa-4152-97d7-5dfb45a8d4ba)'
              azureContainerRegistry: '{"loginServer":"gitopsflowacr.azurecr.io", "id" : "/subscriptions/0fe1cc35-0cfa-4152-97d7-5dfb45a8d4ba/resourceGroups/gitopsrg/providers/Microsoft.ContainerRegistry/registries/gitopsflowacr"}'
              dockerComposeFile: '**/docker-compose.yml'
              projectName: 
              action: 'Build services'
          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscription: 'davete-team(0fe1cc35-0cfa-4152-97d7-5dfb45a8d4ba)'
              azureContainerRegistry: '{"loginServer":"gitopsflowacr.azurecr.io", "id" : "/subscriptions/0fe1cc35-0cfa-4152-97d7-5dfb45a8d4ba/resourceGroups/gitopsrg/providers/Microsoft.ContainerRegistry/registries/gitopsflowacr"}'
              dockerComposeFile: '**/docker-compose.yml'
              projectName: 
              action: 'Push services'
                      

              
              
              
           
           
           