trigger: none

resources:
  pipelines:
  - pipeline: az-vote-ci
    source: 'Azure vote app CI'


variables:
  - group: az-vote-app-dev
  - name: images_artifact_path
    value: $(Pipeline.Workspace)/az-vote-ci/image_tags/s
  - name: manifests_artifact_path
    value: $(Pipeline.Workspace)/az-vote-ci/manifests/s


pool:
  vmImage: ubuntu-latest


stages:
  - stage: "deploy_dev"
    displayName: "Deploy to Dev"
    # variables:
    #   - group: az-vote-app-dev
    jobs:
    - deployment: "Deploy_AzureVote"
      environment: dev
      strategy:
        runOnce:
          deploy:   
            steps:  
              - task: Bash@3        
                name: "Read_Image_tags"
                displayName: "Read Image Tags"
                inputs:
                  targetType: 'inline'
                  script: |
                    # ls -ltr $(images_artifact_path)
                    ls -ltr /home/vsts/work/1/az-vote-ci

        
               
              
              
              
           
           
           