trigger: none

resources:
  pipelines:
  - pipeline: az-vote-ci
    source: 'Azure vote app CI'

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  - group: az-vote-app-dev
  - name: images_artifact_path
    value: $(Pipeline.Workspace)/az-vote-ci/image_tags
  - name: manifests_artifact_path
    value: $(Pipeline.Workspace)/az-vote-ci/manifests
  # - name: utils_artifact_path
  #   value: $(Pipeline.Workspace)/az-vote-ci/utils
  - name: utils_artifact_path
    value: $(Pipeline.Workspace)/cd-utils


pool:
  vmImage: ubuntu-latest

  

stages:
  - stage: "Fetch_the_util_code_temp"
    jobs: 
    - job: "publish_artifacts"
      steps:
      - publish: $(System.DefaultWorkingDirectory)/utils
        artifact: cd-utils


  - stage: "deploy_dev"
    displayName: "Deploy to Dev"    
    jobs:

    - deployment: Deploy_to_dev
      environment: dev
      strategy:
        runOnce:
          deploy:   
            steps:  
            - template: deployment-template.yaml         

    - job: deploy_with_gitops
      dependsOn: Deploy_to_dev
      displayName: Wait for changes to be applied
      pool: server          
      variables:
        pr_num: $[ dependencies.Deploy_to_dev.outputs['Deploy_to_dev.Create_PR.PR_NUM'] ]
      steps:   
      - template: pr-completion-task-template.yaml        

    - job: "Automated_testing"
      displayName: Automated testing 
      dependsOn: deploy_with_gitops
      steps:
      - task: Bash@3        
        name: "smoke_test"
        displayName: "Smoke Test"
        inputs:
          targetType: 'inline'
          script: |
            echo "Place for a smoke test"
            
  - stage: "deploy_stage"
    displayName: "Deploy to Stage"
    variables:
      - group: az-vote-app-stage
    jobs:
    - deployment: Deploy_to_stage
      environment: stage
      strategy:
        runOnce:
          deploy:   
            steps:  
            - template: deployment-template.yaml                      
            

    - job: deploy_with_gitops
      dependsOn: Deploy_to_stage
      displayName: Wait for changes to be applied
      pool: server          
      variables:
        pr_num: $[ dependencies.Deploy_to_stage.outputs['Deploy_to_stage.Create_PR.PR_NUM'] ]
      steps:   
      - template: pr-completion-task-template.yaml                      

    - job: "Automated_testing"
      displayName: Automated testing 
      dependsOn: deploy_with_gitops
      steps:
      - task: Bash@3        
        name: "smoke_test"
        displayName: "Smoke Test"
        inputs:
          targetType: 'inline'
          script: |
            echo "Place for a smoke test"               
              
                     
           