steps:  
  - task: Bash@3        
    name: "Read_Image_tags"
    displayName: "Read Image Tags"
    inputs:
      targetType: 'inline'
      script: |
        for file in $(images_artifact_path)/*; do echo "##vso[task.setvariable variable=${file##*/}]$(cat $file)"; done
  
  # - task: Bash@3        
  #   name: "Generate_Manifests"
  #   displayName: "Generate Manifests"
  #   inputs:
  #     filePath: $(utils_artifact_path)/generate-manifests.sh
  #     arguments: '$(manifests_artifact_path) gen_manifests'
  
  - template: gen-manifest-createpr-template.yaml 

  # - task: Bash@3        
  #   name: "Create_PR"
  #   displayName: "Create PR"
  #   inputs:
  #     filePath: $(utils_artifact_path)/create-pr.sh
  #     arguments: '-s $(Build.SourcesDirectory)/gen_manifests -d $(MANIFESTS_FOLDER) -r $(MANIFESTS_REPO) -b $(MANIFESTS_BRANCH) -i $(Build.BuildNumber) -t $(PAT) -e $(ENVIRONMENT_NAME)'
