steps:
  - task: Bash@3        
    name: "smoke_test"
    displayName: "Smoke Test"
    inputs:
      filePath: $(utils_artifact_path)/smoke-test.sh
      arguments: '$(CLUSTER_ENTRY_URL)$(DEMO_APP_URL)'