# Pipeline to run basic code quality tests as part of pull requests to the master branch.

resources:
  containers:
    - container: mlops
      image: mcr.microsoft.com/mlops/python:latest

pr: none
trigger:
  branches:
    include:
      - master
variables:
  - group: az-vote-app-dev

pool:
  vmImage: "ubuntu-latest"

container: mlops

steps:
  - template: code-quality-template.yaml
  