apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back-{{ .Release.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back-{{ .Release.Name}}
  template:
    metadata:
      labels:
        app: azure-vote-back-{{ .Release.Name}}
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-vote-back-{{ .Release.Name}}
        image: gitopsflowacr.azurecr.io/azvote/redis:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis