apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front-{{ .Release.Name}}
spec:
  type: {{ .Values.serviceType}}
  ports:
  - port: 80
  selector:
    app: azure-vote-front-{{ .Release.Name}}