apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front-{{ .Release.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front-{{ .Release.Name}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-vote-front-{{ .Release.Name}}
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-vote-front
        image: gitopsflowacr.azurecr.io/azvote/azure-vote-front:v3
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: azure-vote-back-{{ .Release.Name}}