apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
stringData:
  notifiers.yaml: |
    webhook:
    - name: test-receiver
      url: http://3e07699bf758.ngrok.io
type: Opaque