apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    webhook:
    - name: test-receiver
      url: http://e811aa34c091.ngrok.io
      # headers:
      # - name: Authorization
      #   value: token <token>
type: Opaque