apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
stringData:
  notifiers.yaml: |
    webhook:
    - name: test-receiver
      url: http://azdo-gitops-events-svc:8080/gitopsphase
      headers:
      - name: Content-Type
        value: application/json
type: Opaque