
name: Stage_Test

on:
  repository_dispatch:
    types: [stage-sync-success]

jobs:
  Test_Dev:
    name: "Test Stage"
    runs-on: ubuntu-latest
    environment: az-vote-app-stage
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Automated test
      run: |
        chmod +x ${{ github.workspace }}/${{ secrets.UTILS_ARTIFACT_PATH }}/smoke-test.sh
        ${{ github.workspace }}/${{ secrets.UTILS_ARTIFACT_PATH }}/smoke-test.sh ${{ secrets.CLUSTER_ENTRY_URL }}${{ secrets.DEMO_APP_URL }}
  