# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches:
      # - master
      - 'brysmith/**'

jobs:
  Build_Push_Azure_Vote_App_Image:
    name: "Build and Push Azure Vote App Image"
    runs-on: ubuntu-latest
    env:
      SRC_FOLDER: azure-vote
      AZ_ACR_NAME: gitopsflowacr
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Create Frontend Image Tags
      env:
        SOURCE_LOCATION: src/azure-vote-front 
        DOCKER_FILE: Dockerfile
        REPOSITORY: azvote/azure-vote-front
        TASKNAME: frontend_image   
      uses: Azure/cli@1.0.4
      with:
        inlineScript:  |
          chmod +x $GITHUB_WORKSPACE/code/buildContainerTemplate.sh
          $GITHUB_WORKSPACE/code/buildContainerTemplate.sh -f $SRC_FOLDER \
                                                           -g $GITHUB_WORKSPACE \
                                                           -s $SOURCE_LOCATION \
                                                           -u $AZ_ACR_NAME \
                                                           -r $REPOSITORY \
                                                           -t $TASKNAME \
                                                           -d $DOCKER_FILE
    - name: Create Backend Image Tags
      env:
        SOURCE_LOCATION: src/azure-vote-back
        DOCKER_FILE: Dockerfile
        REPOSITORY: azvote/azure-vote-back
        TASKNAME: backend_image   
      uses: Azure/cli@1.0.4
      with:
        inlineScript:  |
          chmod +x $GITHUB_WORKSPACE/code/buildContainerTemplate.sh
          $GITHUB_WORKSPACE/code/buildContainerTemplate.sh -f $SRC_FOLDER \
                                                           -g $GITHUB_WORKSPACE \
                                                           -s $SOURCE_LOCATION \
                                                           -u $AZ_ACR_NAME \
                                                           -r $REPOSITORY \
                                                           -t $TASKNAME \
                                                           -d $DOCKER_FILE
    - name: Publish Image Tags
      uses: actions/upload-artifact@v2.2.2
      with:
        name: image_tags
        path: $GITHUB_WORKSPACE/image_tags
    - name: Publish Manifests Templates
      uses: actions/upload-artifact@v2.2.2
      with:
        name: manifests
        path: $GITHUB_WORKSPACE/$SRC_FOLDER/manifests
    - name: Publish utils
      uses: actions/upload-artifact@v2.2.2
      with:
        name: utils
        path: $GITHUB_WORKSPACE/utils
