
name: CD_Stage
 
on:
  repository_dispatch:
    types: [dev-sync-success]
env:
  IMAGE_ARTIFACT_PATH: image_tags
  MANIFEST_ARTIFACT_PATH: azure-vote/manifests
  UTILS_ARTIFACT_PATH: utils
  MANIFESTS_FOLDER: azure-vote-manifests
  MANIFESTS_REPO: https://github.com/kaizentm/gitops-manifests
  PAT: ${{ secrets.PAT }}

jobs:
  Test_Dev:
    name: "Test Dev"
    runs-on: ubuntu-latest
    environment: az-vote-app-dev
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Automated test
      run: |
        chmod +x ${{ github.workspace }}/${{ env.UTILS_ARTIFACT_PATH }}/smoke-test.sh
        ${{ github.workspace }}/${{ env.UTILS_ARTIFACT_PATH }}/smoke-test.sh ${{ secrets.CLUSTER_ENTRY_URL }}${{ secrets.DEMO_APP_URL }}
  Deploy_to_Stage:
      name: "Deploy to Stage"
      runs-on: ubuntu-latest
      needs: Test_Dev
      environment: az-vote-app-stage
      steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Download Image Tags
        uses: dawidd6/action-download-artifact@v2
        with:
          name: image_tags
          workflow: az-vote-cicd.yml
          path: ${{ github.workspace }}/${{ env.IMAGE_ARTIFACT_PATH }}
      - name: Download Manifests Templates
        uses: dawidd6/action-download-artifact@v2
        with:
          name: manifests
          workflow: az-vote-cicd.yml
          path: ${{ github.workspace }}/${{ env.MANIFEST_ARTIFACT_PATH }}
      - name: Download Utils
        uses: dawidd6/action-download-artifact@v2
        with:
          name: utils
          workflow: az-vote-cicd.yml
          path: ${{ github.workspace }}/${{ env.UTILS_ARTIFACT_PATH }}
      - name: Read Image Tags
        run: |
          for file in ${{ github.workspace }}/${{ env.IMAGE_ARTIFACT_PATH }}/*; do echo "##vso[task.setvariable variable=${file##*/}]$(cat $file)"; done 
      - name: Generate Manifests
        run: |
          chmod +x ${{ github.workspace }}/${{ env.UTILS_ARTIFACT_PATH }}/generate-manifests.sh
          ${{ github.workspace }}/${{ env.UTILS_ARTIFACT_PATH }}/generate-manifests.sh $MANIFEST_ARTIFACT_PATH gen_manifests
      - name: Create PR
        run: |
          chmod +x ${{ github.workspace }}/${{ env.UTILS_ARTIFACT_PATH }}/create-pr.sh
          ${{ github.workspace }}/${{ env.UTILS_ARTIFACT_PATH }}/create-pr.sh -s ${{ github.workspace }}/gen_manifests -d $MANIFESTS_FOLDER -r $MANIFESTS_REPO -b ${{ secrets.$MANIFESTS_BRANCH }} -i $GITHUB_RUN_ID -t $PAT -e ${{ secrets.ENVIRONMENT_NAME }} -p ${{ secrets.$PLATFORM }}
